version: '3.7'

services:

    web:    
        container_name: nginx
        build: ./config/docker
        restart: always
        volumes:
            - ./templates:/usr/share/nginx/html          
        command: [nginx-debug, '-g', 'daemon off;']
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=demo01.com
            - NGIKX_PORT=80
